### PR TITLE
Versions update to slim & liquid 3.0 min

### PR DESCRIPTION
**Pull request by dmitryzuev**
Now `sliq` should work with Slim 3.0+ and Liquid 3.0+.

Also need some help to test `on_slim_interpolate` function, it should be great if someone will write tests for this gem.

### CODE REVIEW

**Comment by minad** [comment]
@dmitryzuev Thx! Would you like to maintain the gem?

**Comment by dmitryzuev** [comment]
@minad I'd like to

**Comment by minad** [comment]
@dmitryzuev I invited you and added you as a gem owner here https://rubygems.org/gems/sliq

**Comment by minad** [comment]
@dmitryzuev I also added you to jekyll-slim, since I guess you want to use it with jekyll. Have fun with it :)

**Pull request merged**
